---
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'
          cache: pip

      - run: pip install --upgrade pip-tools
      - run: pip-sync dev-requirements.txt requirements.txt
      - run: make lint
      - run: make test
        env:
          DATABASE_URL: postgres://postgres@localhost:5432/postgres
